@startuml 设备管理模块用例图

left to right direction

actor "学校管理员" as Admin

usecase "设备注册" as UC1
usecase "设备状态监控" as UC2
usecase "设备信息编辑" as UC3
usecase "设备删除" as UC4

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4

UC1 .> UC2 : <<include>>
UC3 .> UC2 : <<include>>
UC4 .> UC2 : <<include>>

@enduml